### ISSUE TITLE
Check if translate-src directory is already present

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [arkadianriver/sphinx-translate-test#1]
When I run the run.sh script for the second time, the script fails with error:

`mkdir: cannot create directory ‘translate-src’: File exists`.

So when we need to update the translation po files, we may run run.sh multiple times? In that case, should there be a condition to check if `translate-src` folder already exists? What is the need of this folder?

**Comment by arkadianriver** [comment]
aha.. thanks! This script was originally intended for a clean CI build, but yeah.. fixed for repeated use. 🚀
